# Generated by Django 6.1 on 2026-08-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_lead_lifecycle_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='lead_lifecycle_timer_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
