# Generated by Django 5.0.14 on 2026-09-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_default_lead_lifecycle_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='gbp_to_ngn_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=2000.0, max_digits=12, null=True),
        ),
    ]
