# Generated by Django 5.0.14 on 2026-09-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organization_parcel_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='doorstep_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
