# Generated by Django 6.1 on 2026-08-27 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_default_lead_lifecycle_days_and_more'),
        ('crm', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to='accounts.team'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_active_lead',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='lifecycle_extension_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='lifecycle_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='lifecycle_status',
            field=models.CharField(default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.stage'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CustomerList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('list_type', models.CharField(choices=[('STATIC', 'Static'), ('SMART', 'Smart')], default='STATIC', max_length=50)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('contacts', models.ManyToManyField(blank=True, related_name='customer_lists', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_lists', to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('singular_name', models.CharField(max_length=255)),
                ('icon', models.CharField(default='Grid', max_length=100)),
                ('fields', models.JSONField(default=list)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_modules', to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomModuleRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('custom_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='crm.custommodule')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_module_records', to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadLifecycleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.IntegerField(db_index=True)),
                ('action_type', models.CharField(choices=[('CREATE_TASK', 'Create Task'), ('NOTIFY_EMPLOYEE', 'Notify Employee'), ('NOTIFY_MANAGER', 'Notify Manager'), ('CHANGE_STAGE', 'Change Stage'), ('MARK_INACTIVE', 'Mark Inactive')], max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_lifecycle_rules', to='accounts.organization')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
