# Generated by Django 6.1 on 2026-08-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_company_custom_fields_contact_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
