# Generated by Django 5.0.14 on 2026-09-03 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_default_lead_lifecycle_days_and_more'),
        ('crm', '0007_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=100)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=50)),
                ('receiver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_tel', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_email', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_address', models.TextField(blank=True, null=True)),
                ('total_value_items', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expected_parcel_no', models.CharField(blank=True, max_length=100, null=True)),
                ('parcel_handler', models.CharField(blank=True, max_length=150, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('services', models.JSONField(blank=True, default=list)),
                ('total_ngn', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_gbp', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('sla_terms_url', models.CharField(default='https://www.mintana.co.uk/terms-and-conditions', max_length=500)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.deal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid_ngn', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('amount_paid_gbp', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payment_method', models.CharField(default='BANK_TRANSFER', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('items_summary', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='crm.contact')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='crm.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
