# Generated by Django 5.0.14 on 2026-09-05 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_default_lead_lifecycle_days_and_more'),
        ('crm', '0009_contact_city_contact_lead_acquisition_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('CONTACT', 'Contact'), ('CUSTOMER', 'Customer'), ('PARTNER', 'Partner')], db_index=True, default='LEAD', max_length=100),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_email', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_address', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shipment_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CUSTOMS_HOLD', 'Customs Hold'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=50)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=50)),
                ('currency', models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GBP', 'GBP')], default='NGN', max_length=10)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_carton', models.IntegerField(default=1)),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_received', models.TextField(blank=True, null=True)),
                ('items_shipped', models.TextField(blank=True, null=True)),
                ('items_recieved', models.TextField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tracking_id', models.CharField(db_index=True, max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='accounts.organization')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_shipments', to='crm.contact')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_shipments', to='crm.contact')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_shipments', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_shipments', to='crm.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
