# Generated by Django 5.0.14 on 2026-09-07 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_default_lead_lifecycle_days_and_more'),
        ('crm', '0010_alter_contact_status_shipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('escalation_type', models.CharField(choices=[('DELAY', 'Delay in Delivery'), ('DAMAGED_GOODS', 'Damaged Goods'), ('MISSING_ITEM', 'Missing Item/Package'), ('BILLING_ISSUE', 'Billing / Overcharge Issue'), ('CUSTOMS_HOLD', 'Customs Hold / Documentation'), ('WRONG_DELIVERY', 'Wrong Delivery Address'), ('OTHER', 'Other')], default='DELAY', max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent / Critical')], default='MEDIUM', max_length=50)),
                ('complaint_summary', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=50)),
                ('internal', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipment_escalations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_escalations', to='crm.contact')),
                ('escalation_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipment_escalations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_escalations', to='accounts.organization')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='crm.shipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
