# Generated by Django 6.1 on 2026-09-08 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_default_lead_lifecycle_days_and_more'),
        ('crm', '0011_shipmentescalation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSRReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily Report'), ('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report')], db_index=True, default='DAILY', max_length=50)),
                ('new_enquiries', models.IntegerField(default=0)),
                ('packages_expected', models.IntegerField(default=0)),
                ('quotation_sent', models.IntegerField(default=0)),
                ('shipment_booked', models.IntegerField(default=0)),
                ('outstanding_follow_up', models.IntegerField(default=0)),
                ('customer_complaint_resolved', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('packages_received', models.IntegerField(default=0)),
                ('customer_converted_paid', models.IntegerField(default=0)),
                ('follow_up_completed', models.IntegerField(default=0)),
                ('customer_complaint_received', models.IntegerField(default=0)),
                ('customer_escalated_to_manager', models.IntegerField(default=0)),
                ('shipment_delays_and_reason', models.TextField(blank=True, null=True)),
                ('biggest_challenge_week', models.TextField(blank=True, null=True)),
                ('support_needed', models.TextField(blank=True, null=True)),
                ('biggest_achievement_week', models.TextField(blank=True, null=True)),
                ('suggestion_for_improvement', models.TextField(blank=True, null=True)),
                ('social_media_follows_encouraged', models.IntegerField(default=0)),
                ('video_testimonial_received', models.IntegerField(default=0)),
                ('biggest_challenge_month', models.TextField(blank=True, null=True)),
                ('biggest_achievement_month', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csr_reports', to='accounts.organization')),
                ('reported_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csr_reports_received', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csr_reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
