# Generated by Django 5.0.14 on 2026-09-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_csrreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='sender_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
