# Generated by Django 5.0.14 on 2026-09-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrreport',
            name='month_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
