# Generated by Django 5.0.14 on 2026-09-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_csrreport_month_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('AIR', 'Air Freight'), ('SEA', 'Sea Shipping')], default='AIR', max_length=20, null=True),
        ),
    ]
