# Generated by Django 5.0.14 on 2026-09-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_shipment_discount_percentage_shipment_shipping_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
