# Generated by Django 5.0.14 on 2026-09-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_shipment_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='has_doorstep_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
