# Generated by Django 5.0.14 on 2026-09-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_shipment_has_doorstep_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
