# Generated by Django 6.1 on 2026-09-13 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organization_per_kg_price'),
        ('crm', '0019_shipment_shipment_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceScorecard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scorecard_type', models.CharField(choices=[('CS_AGENT_WEEKLY', 'Customer Support Agent Weekly Performance Scorecard'), ('CS_AGENT_MONTHLY', 'Customer Support Agent Monthly Performance Scorecard'), ('SM_MANAGER_WEEKLY', 'Social Media Manager Weekly Performance Scorecard'), ('SM_MANAGER_MONTHLY', 'Social Media Manager Monthly Performance Scorecard')], db_index=True, max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('period_label', models.CharField(blank=True, max_length=100, null=True)),
                ('kpi_evaluations', models.JSONField(blank=True, default=list)),
                ('activity_metrics', models.JSONField(blank=True, default=list)),
                ('performance_metrics', models.JSONField(blank=True, default=list)),
                ('total_score', models.FloatField(default=0.0)),
                ('performance_rating', models.CharField(choices=[('OUTSTANDING', 'Outstanding (90–100%)'), ('VERY_GOOD', 'Very Good (80–89%)'), ('GOOD', 'Good (70–79%)'), ('NEEDS_IMPROVEMENT', 'Needs Improvement (60–69%)'), ('UNSATISFACTORY', 'Unsatisfactory (Below 60%)')], default='GOOD', max_length=50)),
                ('key_strengths', models.TextField(blank=True, null=True)),
                ('areas_for_improvement', models.TextField(blank=True, null=True)),
                ('challenges_issues', models.TextField(blank=True, null=True)),
                ('key_achievement', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('team_lead_comment', models.TextField(blank=True, null=True)),
                ('evaluator_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluator_signature_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_scorecards_received', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_scorecards_evaluated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scorecards', to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
