# Generated by Django 5.0.14 on 2026-09-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_performancescorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='dpd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='packager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
