# Generated by Django 6.1 on 2026-10-04 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_must_change_password'),
        ('crm', '0021_shipment_dpd_shipment_packager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='DailyManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('access_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_manifests', to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'date')},
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='manifest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='crm.dailymanifest'),
        ),
    ]
