# Generated by Django 6.1 on 2026-10-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_contact_email_dailymanifest_shipment_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentescalation',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
