# Generated by Django 6.1 on 2026-10-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_shipmentescalation_last_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_received_by_customer',
            field=models.BooleanField(default=False),
        ),
    ]
