# Generated by Django 6.1 on 2026-10-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_shipment_is_received_by_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='dpd_tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
