# Generated by Django 6.1.1 on 2026-10-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_shipment_is_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='promo_doorstep_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='promo_packaging_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
