# Generated by Django 5.0 on 2026-10-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_shipment_promo_doorstep_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='original_total_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_total_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
