# Generated by Django 5.0.14 on 2026-10-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_invoice_original_total_gbp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sender_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_tel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
