# Generated by Django on 2026-10-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_shipment_has_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=15),
        ),
    ]
