# Generated by Django 5.0.14 on 2026-10-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_shipment_extra_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='video_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='video_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
