# Generated by Django 6.1 on 2026-08-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='creator',
            new_name='performed_by',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('NOTE', 'Note')], db_index=True, max_length=50),
        ),
    ]
