# Generated by Django 6.1 on 2026-08-27 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_contact_assigned_team_contact_is_active_lead_and_more'),
        ('planning', '0003_task_attachments_task_checklist_task_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.project'),
        ),
    ]
