# Generated by Django 6.1 on 2026-09-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_contact_status_shipment'),
        ('planning', '0005_activity_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_tasks', to='crm.contact'),
        ),
    ]
