# Generated by Django 5.0.14 on 2026-09-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_task_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='partner',
        ),
    ]
